### ISSUE TITLE
Release merged PR #185 (Classnames beginning with numbers)

### ISSUE THREAD

**Issue by mattwaler** [FullHuman/postcss-purgecss#34]
I see that there was a PR that was merged into master:
[Ensure classes beginning with numbers are properly purged #185](https://github.com/FullHuman/purgecss/pull/185)

However, there is no easy way to install this fix and start using through NPM. Could you release this new version?

Thanks!!

**Comment by Ffloriel** [comment]
done with the new version

**Comment by mattwaler** [comment]
Awesome!! Thanks!
