### ISSUE TITLE
Class constructor extractor cannot be invoked without 'new'  

### ISSUE THREAD

**Issue by NaciAkce** [FullHuman/postcss-purgecss#57]
Get an error with the PurgeCss Version 2.0.5 and gulp-postcss

`events.js:187
      throw er; // Unhandled 'error' event
      ^
PluginError [TypeError]: Class constructor extractor cannot be invoked without 'new'
    at extractSelectors (/node_modules/purgecss/lib/purgecss.js:1:2358)`

Full Error
`
    at Transform.emit (events.js:210:5)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:452:5)
    at onwrite (_stream_writable.js:473:5)
    at Transform.afterTransform (_stream_transform.js:96:3)
    at Immediate.<anonymous> (.../node_modules/gulp-postcss/index.js:93:9)
    at processImmediate (internal/timers.js:439:21) {
  message: "Class constructor extractor cannot be invoked without 'new'",
  name: 'TypeError',
  stack: "TypeError: Class constructor extractor cannot be invoked without 'new'\n" +
    '    at extractSelectors (.../node_modules/purgecss/lib/purgecss.js:1:2358)\n' +
    '    at PurgeCSS.extractSelectorsFromFiles (.../node_modules/purgecss/lib/purgecss.js:1:5802)\n' +
    '    at async .../node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:501\n' +
    "Emitted 'error' event on Transform instance at:\n" +
    '    at Transform.onerror (.../node_modules/readable-stream/lib/_stream_readable.js:640:52)\n' +
    '    at Transform.emit (events.js:210:5)\n' +
    '    at errorOrDestroy (internal/streams/destroy.js:107:12)\n' +
    '    at onwriteError (_stream_writable.js:452:5)\n' +
    '    at onwrite (_stream_writable.js:473:5)\n' +
    '    at Transform.afterTransform (_stream_transform.js:96:3)\n' +
    '    at Immediate.<anonymous> (.../node_modules/gulp-postcss/index.js:93:9)\n' +
    '    at processImmediate (internal/timers.js:439:21)',
  __safety: undefined,
  _stack: undefined,
  plugin: 'gulp-postcss',
  showProperties: true,
  showStack: true,
  fileName: '.../src/assets/Scss/styles.css'
`

**Comment by Ffloriel** [comment]
https://github.com/FullHuman/purgecss/issues/276
